### ISSUE TITLE
Support all the ANSI escape codes for styling

### ISSUE THREAD

**Issue by rgbkrk** [IonicaBizau/ansi-to-json#2]
* [ ] `[1m`/bold  	Set "bright" attribute
* [ ] `[2m`/dim		Set "dim" attribute
* [ ] `[4m`/smul 	Set "underscore" (underlined text) attribute
* [ ] `[5m`/blink 	Set "blink" attribute
* [ ] `[7m`/rev    	Set "reverse" attribute
* [ ] `[8m`/invis 	Set "hidden" attribute

[Code ref](http://wiki.bash-hackers.org/scripting/terminalcodes)

**Comment by IonicaBizau** [comment]
@rgbkrk That's definitely a thing! :+1: Like I mentioned in a private conversation, I'm going to maintain a separate project based on [`ansi_up`](https://github.com/drudru/ansi_up). There we should take care of these features.

**Comment by rgbkrk** [comment]
That sounds good.

**Comment by IonicaBizau** [comment]
@rgbkrk OK, so due to the lack of feedback to my PR in the original repo, I decided to create and maintain my own package: https://github.com/IonicaBizau/anser :rocket:

**Comment by IonicaBizau** [comment]
:ship: **`1.0.1`** :tada: This library is now using `anser` over `ansi_up`.

**Comment by IonicaBizau** [comment]
Moving this here: https://github.com/IonicaBizau/anser/issues/1

**Comment by rgbkrk** [comment]
:smile: Thanks @IonicaBizau, looks like a good direction.
